/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "Vin_1.h"
#include "Vin_1_aliases.h"
#include "Vin_2.h"
#include "Vin_2_aliases.h"
#include "UART.h"
#include "isr_RX.h"
#include "Vin_3.h"
#include "Vin_3_aliases.h"
#include "Vin_4.h"
#include "Vin_4_aliases.h"
#include "Control.h"
#include "Timer.h"
#include "isr_1.h"
#include "Status.h"
#include "Vin_5.h"
#include "Vin_5_aliases.h"
#include "Vin_6.h"
#include "Vin_6_aliases.h"
#include "Vin_7.h"
#include "Vin_7_aliases.h"
#include "Vin_8.h"
#include "Vin_8_aliases.h"
#include "Vin_9.h"
#include "Vin_9_aliases.h"
#include "Vin_10.h"
#include "Vin_10_aliases.h"
#include "Vin_11.h"
#include "Vin_11_aliases.h"
#include "Vin_12.h"
#include "Vin_12_aliases.h"
#include "Vin_13.h"
#include "Vin_13_aliases.h"
#include "Vin_14.h"
#include "Vin_14_aliases.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

